name: siedlungundberufe
version: '1.21.1'
main: me.marc3308.siedlungundberufe.Siedlungundberufe
api-version: '1.21'

permissions:
  siedlungsmod:
    description: Darf siedlungen erstellen

commands:
  Siedlung:
    description: Open a Gui for creation and editing of your Siedlung
    permission: siedlungsmod
  loadsiedlungyml:
    description: load the siedlungsyms´l
  savesiedlungen:
    description: saves the siedlungen in the yml
  einladung:
    description: a siedlungs invite
